import operator
from typing import Annotated

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


class SubtaskFinding(TypedDict):
    subtask: str
    claim: str
    evidence_span: str
    citation_url: str


class Clarification(TypedDict):
    question: str
    answer: str


# WORKING MEMORY (layer 1 of the memory stack):
# Typed LangGraph state — the in-run scratchpad passed between all nodes.
# Persisted per thread_id by the Postgres checkpointer (layer 3).
class ResearchState(TypedDict):
    run_id: str
    query: str
    # Questions generated by the clarify node, pending user answers
    clarification_questions: list[str]
    # Clarifying questions asked + user answers (human-in-the-loop, layer 3)
    clarifications: list[Clarification]
    # Supervisor's free-text reasoning about how to approach the query (plan node)
    supervisor_thinking: str
    # Sub-questions produced by the plan node
    subtasks: list[str]
    # operator.add reducer accumulates findings from all parallel subagents
    findings: Annotated[list[SubtaskFinding], operator.add]
    # Populated by the compact node (context compaction, layer 2)
    summary: str
    # Final cited Markdown report written by the synthesize node
    report: str
    # add_messages reducer enables multi-turn follow-up chat (layer 3)
    messages: Annotated[list[BaseMessage], add_messages]


class SubagentInput(TypedDict):
    """Payload sent to each subagent via Send fan-out. Not the full graph state."""
    question: str
